### ISSUE TITLE
What specifications is this EFI based on?

### ISSUE THREAD

**Issue by aiSanaul** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#10]
I see various specs in this tower, out there:
- i5 6th
- i3 4th
- i7 6th
Does this work on every model?
Please answer this question. I really appreciate the help.

**Comment by mavethee** [comment]
**_It's Kaby Lake_**
![image](https://github.com/user-attachments/assets/f966d70a-063a-46a5-9510-050192cbf9be)

**Comment by aiSanaul** [comment]
Um... can you help me make one for OptiPlex 3050 Skylake (i5 6400) for installing Sierra?
