### ISSUE TITLE
Dell 3050 sff

### ISSUE THREAD

**Issue by R3n09** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#11]
Hello and thank you for your great job

I tried your EFi to install sequoia but I was unable to do so in 3050sff

I have a working EFI for Sonoma,can you kindly help me modify it so I  can achieve to install sequoia please?

**Comment by ryanhaven** [comment]
I have same the same issue

**Comment by mavethee** [comment]
@R3n09 @ryanhaven 

List your specs or I'm closing it.

It's not proper way to report issues, use your words and RTFM.

**Comment by ryanhaven** [comment]
Issue resolved.
Updated kexts and core to latest versions.
