### ISSUE TITLE
Model of Dell OptiPlex 3050

### ISSUE THREAD

**Issue by AlexandreC31** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#2]
Hello men, this opencore projet is for dell optiplex 3050 micro or for standard ? 
thx

**Comment by mavethee** [comment]
It's for standard one, you can see i3-7100 in neofetch, not T one which is in micros I believe.

**Comment by AlexandreC31** [comment]
Do you have a idea with : AppleKeyStore:869 error ?
