### ISSUE TITLE
Does this work for the 3050 SFF?   

### ISSUE THREAD

**Issue by hungtru** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#5]
I tried this with the 3050 SFF with i5, but having problems.  
Wondering if that was for the 3050 SFF or MFF...

Thoughts?

**Comment by mavethee** [comment]
If it's still Kaby Lake, then yes and no ;)

Firstly, NVMe SSDs:
- [If you have it, make sure to check if it's compatible](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html), 
- If it is, then don't forget about [NVMeFix](https://github.com/acidanthera/NVMeFix) and flashing your config).

Check this for refrence how to tweak the EFI up to match up your config more, mentioned in different issues:

https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050/issues/6#issuecomment-1509960419 or https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050/issues/3#issuecomment-1399420439

If we speak totally different Intel generation then just follow [Dortania's Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/#intel-desktop) for necessary changes in config.plist.
