### ISSUE TITLE
APPLEKEYSTOREEVENT FAILED TO ALLOC CLASS

### ISSUE THREAD

**Issue by snoozyi** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#6]
![IMG_0737](https://user-images.githubusercontent.com/58711480/232250827-ccdf14cf-58e8-4942-a050-6eab26f452d4.jpg)
![IMG_0738](https://user-images.githubusercontent.com/58711480/232250829-2b49b3ed-17bd-4bcd-b8a5-738b91b5a354.jpg)
macOS Ventura 13.3.1 
I3 7th Gen
16GBs of ram
128 SSD (not M.2)

Tried diffrent USB's 
Rebuilding it

Had no luck,

**Comment by mavethee** [comment]
AppleKeyStore stuff is general thing, not your issue.

0. Make sure, everything is up to date, BIOS, Firmware etc.

1. Validate your BIOS settings:
https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#intel-bios-settings

Depending on issue, being up to date or correct BIOS settings should do the trick, if not, well here it goes:

2. Dump own SSDTs using SSDTTime:

-  https://github.com/corpnewt/SSDTTime
(Dump DSDT, then FixEC, USBX, FixHPET, PluginType)

- Replace aml files in ACPI folder

3. USB Mapping:

- Remove USBInjectAll from Kexts folder, 
- Using Windows map your USBs using [USBToolBox](https://github.com/USBToolBox/tool). Remember to read [Usage](https://github.com/USBToolBox/tool#usage) in README.

4. Flash your config.plist with [ProperTree](https://github.com/corpnewt/ProperTree) (Ctrl + R, enter, Ctrl + S):

5. If you have issues with HDMI/DP, check [Patching connectors-type in Modern Intel iGPUs](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html#patching-connector-types).

**Comment by mavethee** [comment]
Closing due inactivity.
