### ISSUE TITLE
Update to OC 0.9.2

### ISSUE THREAD

**Issue by drewb0y** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#7]
How difficult would it be to update your EFI folder to OpenCore 0.9.2 before installing? Thanks!

**Comment by mavethee** [comment]
> How difficult would it be to update your EFI folder to OpenCore 0.9.2 before installing? Thanks!

Assuming you have perfectly same config, just by replacing

- /EFI/OC/BOOT/BOOTx64.efi
- Every efi inside /EFI/OC/Drivers

and Kexts obviously.

https://dortania.github.io/OpenCore-Post-Install/universal/update.html

As I've finished school I tend to play safe with this machine hah.

Sonoma should boot as well with supported SMBIOS but kexts might be removed in like beta 7 like in Kepler and Monterey case, so prepare for KBL -> CFL spoofing in future.

Will update repo if I will figure out key changes for macOS 14

**Comment by drewb0y** [comment]
Awesome thanks - Yeah mine is a pretty vanilla 3050 just like yours so all the files should be the same - just figured it would be good to update the OC before installing - It'll be interesting to see if Sonoma works as well. I'll follow you here and on Reddit for any updates you post.

**Comment by mavethee** [comment]
> Awesome thanks - Yeah mine is a pretty vanilla 3050 just like yours so all the files should be the same - just figured it would be good to update the OC before installing - It'll be interesting to see if Sonoma works as well. I'll follow you here and on Reddit for any updates you post.

Closing then if that's all! ^-^

Might be cool to get reference pic for README for Sonoma if you don't mind sending haha.
