### ISSUE TITLE
Problem during installation of Sonoma

### ISSUE THREAD

**Issue by R3n09** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#8]
Hello and thank you for your hard work,

I am unable to install Sonoma with the given EFI file.

I have changed the iMac model to imac19,1 via opencore and generated again the EFI via the generate EFI to desktop option(also changed the smbios via the opencore it self and inserted all necessary kext files)

My 3050 has an i5 7th gen processor

But my installation stacks on the code just before the installation wizard ,my hard disk controller is unsupported as I see but I assume it would get me atleast to the installation wizard.

Can you please assist?

**Comment by ybmmike** [comment]
I followed the guide from https://dortania.github.io/OpenCore-Install-Guide/ to create my USB installation for Ventura.
I also have 7th gen CPU.
But i just was not able to get the onboard audio to work until I found EFI by mavethee.   I compared his EFI to mine and there was section for patching something.   I copied that in and boom! audio was working.
After that... all I did was run the system os update directly from MacOS itself and I was able to update to Sonoma and all seems to work fine.
Not the exact help but I thought it may help.   

By the way mavethee have a video on youtube on how he built the usb installer.   music is very annoying but still useful.

**Comment by R3n09** [comment]
The problem that I am facing is related to installation with Sonoma

I have used the given EFI but after selecting installing Sonoma it halts at this line 

Applelockdownmode -LDMShouldenforceparity) restore os check passed

Or to the line lockdown mode: lockdown mode in nvram is off

**Comment by mavethee** [comment]
Key to success, is understand the whole process anyways, despite model being the same, it rarely is the same machine.

I'd start with validating BIOS settings:
https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#intel-bios-settings

If still doesn't work, download SSDTTime, generate your own SSDTs for ACPI:
https://github.com/corpnewt/SSDTTime

- Generate own DSDT,
- Select:
a) select `FixEC` for `SSDT-EC`,
b) select `PluginType` for `SSDT-PLUG`,
c) select `USBX` for `SSDT-USBX`,
d) select `Fix IRQ conflicts` for `SSDT-HPET`.

- Delete `.dsl` files, swap aml files in `EFI/OC/ACPI`.

Re-doing USB mapping with USBToolBox is useful as well:
https://github.com/USBToolBox/tool
https://github.com/USBToolBox/kext
https://github.com/USBToolBox/tool#usage

In case of using NVMe drives, kext needs to be added:
https://github.com/acidanthera/NVMeFix

Re-snapshot your config.plist using ProperTree:
https://github.com/corpnewt/ProperTree

**_Usually, first step is enough as a lot of people don't pay attention to check BIOS settings._**

**Comment by mavethee** [comment]
> I followed the guide from https://dortania.github.io/OpenCore-Install-Guide/ to create my USB installation for Ventura. I also have 7th gen CPU. But i just was not able to get the onboard audio to work until I found EFI by mavethee.

Great to hear that, my guess is you missed to setup layout-id, provided in EFI is just first from the list iirc:
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

`alcid=xx` in `NVRAM -> [UUID] -> boot-args`.

> I compared his EFI to mine and there was section for patching something. I copied that in and boom! audio was working. After that... all I did was run the system os update directly from MacOS itself and I was able to update to Sonoma and all seems to work fine. Not the exact help but I thought it may help.

only "patching" present is for HDMI, this part specifically but I probably misunderstood
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html

> By the way mavethee have a video on youtube on how he built the usb installer. music is very annoying but still useful.

**_I don't provide any youtube guides,_** only one proper guide is text guide here:
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by R3n09** [comment]
I was finally able to install Sonoma with an EFI that was shared to be from a user in a hackinosh forum,if you are interested I can share the file.thank you very much for the valuable guidance

**Comment by ybmmike** [comment]
Good to hear that you have it installed.   Did all the onboard components work or did you had to do some post-install stuff?
Yes, please do share.  I would like to have a look at it and compare.

**Comment by R3n09** [comment]
Hello,

From a quick look everything works out of the box

I am going to have a look these days and see if I encourage some issues.

How can I send you the EFI folder?

**Comment by hah100** [comment]
> I was finally able to install Sonoma with an EFI that was shared to be from a user in a hackinosh forum,if you are interested I can share the file.thank you very much for the valuable guidance

Can you share this EFI with me please? I want to install Sonoma on an Optiplex 3070 mff. All the EFI's I found so far get stuck.
