### ISSUE TITLE
Does this work with the SFF (small form factor) 

### ISSUE THREAD

**Issue by Pandaman123456** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#9]
I have the OptiPlex 3050 SFF, and would like to know if this efi works for that pc.

**Comment by mavethee** [comment]
This is for config.plist is mostly for any Desktop Kaby Lake devices with Dell specific tweaks on.
Even if you have the same model, my bet is ACPI neds to be redumped for your device, same with USBMap and SMBIOS to regenerate, so if you have 7th gen Intel model, then yes, if it's Skylake then config.plist needs to be re-done.
